name = "ecode-internal-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "ecode-db"
database_id = "40516caa-63d7-4ff5-bb3f-7b920cc3a409"

[[r2_buckets]]
binding = "FILES"
bucket_name = "ecode-files"

[durable_objects]
bindings = [
  { name = "WEBSOCKET_ROOM", class_name = "WebSocketRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WebSocketRoom"]
